- name: Install Galera on CentOS Servers
  yum:
      name: "{{ item }}"
      state: present
      with_items:
      - galera-3
      - galera-arbitrator-3
      - mysql-wsrep-5.6
  become: true
  when: ansible_os_family == "CentOS"

- name: Install Galera on Debian Servers
  apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
  with_items:
      - galera-3
      - galera-arbitrator-3
      - mysql-wsrep-5.6
      - python-mysqldb
      - rsync
  become: true
  when: ansible_os_family == "Debian"
