- name: Ensure MariaDB is running
  service:
    name: mariadb
    state: started
  become: true

- name: Cleanup Galera default config files
  file:
    name: "{{ item }}"
    state: absent
  with_items:
    - /etc/mysql/conf.d/mariadb.cnf
    - /etc/mysql/conf.d/server.cnf
  become: true

- name: Add Galera User
  notify: Bootstrap Galera
  mysql_user:
    name: "{{ galera_user }}"
    password: "{{ galera_pass }}"
    priv: "*.*:ALL"
    host: "localhost"
    append_privs: yes
  become: true

- name: Add confluence database
  mysql_db:
    name: confluence
    state: present
    encoding: utf8
    collation: utf8_bin
  become: true

- name: Add Confluence user
  mysql_user:
    name: confluence_user
    password: confluence_password
    priv: "confluence.*:ALL"
    host: '%'
    append_privs: yes
  become: true

- name: Add galera configuration
  notify: Restart Galera Cluster
  template:
      src: server.cnf.j2
      dest: /etc/mysql/conf.d/galera.cnf
      owner: root
      group: root
      mode: 0644
  become: true
