- name: Install MySQL Repository Key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "{{ item }}"
  loop:
    - BC19DDBA
  become: true

- name: Install Galera Repository
  apt_repository:
    repo: "{{ item }}"
    state: present
    filename: Galera
  loop:
    - deb http://releases.galeracluster.com/mysql-wsrep-5.6/ubuntu xenial main
    - deb http://releases.galeracluster.com/galera-3/ubuntu xenial main
  become: true

- name: Configure Preference for Codership repository
  template:
    src: ../templates/Galera.pref.j2
    dest: /etc/apt/preferences.d/Galera.pref
  become: true
