# Bootstrap
- name: Stop MySQL on first Galera cluster node
  listen: Bootstrap Galera
  service:
    name: mysql
    state: stopped
  become: true
  when: (inventory_hostname == groups['DB_Cluster'][0])

- name: Bootstrap first Galera cluster node
  listen: Bootstrap Galera
  command: /etc/init.d/mysql start --wsrep-new-cluster
  become: true
  when: (inventory_hostname == groups['DB_Cluster'][0])

- name: Restart MySQL on the other Galera cluster nodes
  listen: Bootstrap Galera
  service:
    name: mysql
    state: restarted
  become: true
  when: (inventory_hostname != groups['DB_Cluster'][0])

